# Generated by Django 4.1.3 on 2022-12-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, null=True, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, null=True, verbose_name="Фамилия"),
                ),
                (
                    "birth_date",
                    models.DateField(null=True, verbose_name="Дата рождения"),
                ),
                (
                    "login",
                    models.CharField(max_length=10, null=True, verbose_name="login"),
                ),
                (
                    "password",
                    models.CharField(max_length=100, null=True, verbose_name="Пароль"),
                ),
                ("about", models.TextField(null=True, verbose_name="О себе")),
                (
                    "github_link",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Ccылка на github"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Ник в телеграм"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Специализация"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=200, null=True, verbose_name="Почта"),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
            ],
            options={
                "verbose_name": "Аккаунт",
                "verbose_name_plural": "Аккаунты",
                "db_table": "accounts",
            },
        ),
    ]
