# Generated by Django 4.1.3 on 2022-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="birth_date", new_name="birthdate",
        ),
        migrations.AlterField(
            model_name="users",
            name="login",
            field=models.CharField(max_length=10, null=True, verbose_name="Логин"),
        ),
    ]
