# Generated by Django 4.1.4 on 2022-12-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='accounts',
        ),
    ]
