# Generated by Django 4.1.3 on 2022-12-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_birth_date_users_birthdate_alter_users_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="profile_pic", new_name="profile_picture",
        ),
        migrations.RemoveField(model_name="users", name="github_link",),
        migrations.RemoveField(model_name="users", name="phone_number",),
        migrations.RemoveField(model_name="users", name="specialization",),
        migrations.RemoveField(model_name="users", name="telegram",),
    ]
