# Generated by Django 4.1.3 on 2022-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_users_email_alter_users_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="about",
            field=models.TextField(max_length=10000, null=True, verbose_name="О себе"),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=10000, null=True, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=10000, null=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="users",
            name="login",
            field=models.CharField(max_length=10000, null=True, verbose_name="Логин"),
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=10000, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=10000, null=True, verbose_name="Пароль"),
        ),
    ]
