# Generated by Django 4.1.4 on 2022-12-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_table'),
        ('account', '0005_alter_users_about_alter_users_email_and_more'),
    ]

    operations = [
    ]
