# Generated by Django 4.1.4 on 2022-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Дата рожденияz'),
        ),
    ]
