# Generated by Django 4.1.4 on 2022-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='images'),
        ),
    ]
