# Generated by Django 4.1.4 on 2022-12-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_users_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
    ]
