# Generated by Django 4.1.4 on 2022-12-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_users_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=1, null=True, verbose_name='Статус активности'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatars/avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
