# Generated by Django 4.1.4 on 2022-12-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_users_status_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='Книгоман', max_length=10000, null=True, verbose_name='Имя'),
        ),
    ]
