# Generated by Django 4.1.4 on 2023-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_users_is_onboarding_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pages_per_day',
            field=models.IntegerField(default=10, null=True, verbose_name='Количество страниц в день'),
        ),
    ]
