# Generated by Django 4.1.3 on 2022-12-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authors",
            name="about_author",
            field=models.TextField(null=True, verbose_name="Об авторе"),
        ),
    ]
