# Generated by Django 4.1.3 on 2022-12-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_alter_authors_about_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="authors", name="about_author",),
        migrations.RemoveField(model_name="authors", name="birthdate",),
        migrations.RemoveField(model_name="authors", name="popular_books",),
    ]
