# Generated by Django 4.1.3 on 2022-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0004_remove_authors_last_name_alter_authors_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="authors", name="name",),
        migrations.RemoveField(model_name="authors", name="profile_picture",),
        migrations.AddField(
            model_name="authors",
            name="author_name",
            field=models.CharField(max_length=10000, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="authors",
            name="author_pic",
            field=models.URLField(
                max_length=10000, null=True, verbose_name="Ссылка на фото автора"
            ),
        ),
    ]
