# Generated by Django 4.1.4 on 2022-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_authors_name_remove_authors_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='author_description',
            field=models.TextField(null=True, verbose_name='Коротко об авторе'),
        ),
    ]
