# Generated by Django 4.1.4 on 2023-05-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0004_remove_genres_creat_date'),
        ('account', '0016_alter_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.genres')),
            ],
            options={
                'verbose_name': 'Избранные жанры для пользователя',
                'verbose_name_plural': 'Избранный жанр для пользователя',
                'db_table': 'favorites_genres',
            },
        ),
    ]
