# Generated by Django 4.1.4 on 2023-05-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritesgenres',
            options={'verbose_name': 'Избранный жанр для пользователя', 'verbose_name_plural': 'Избранные жанры для пользователя'},
        ),
        migrations.RenameField(
            model_name='favoritesgenres',
            old_name='books_id',
            new_name='account_id',
        ),
    ]
