# Generated by Django 4.1.4 on 2023-05-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0004_remove_genres_creat_date'),
        ('authors', '0006_authors_author_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10000, null=True, verbose_name='Название книги')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Оценка')),
                ('pages_count', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('description', models.TextField(max_length=10000, null=True, verbose_name='Описание')),
                ('pic_link', models.URLField(max_length=10000, null=True, verbose_name='Ссылка на картинку')),
                ('book_link', models.URLField(max_length=10000, null=True, verbose_name='Ссылка на книгу')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authors')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.genres')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'books',
            },
        ),
    ]
