# Generated by Django 4.1.4 on 2023-05-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_authors_author_description'),
        ('genres', '0004_remove_genres_creat_date'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genres.genres'),
        ),
    ]
