# Generated by Django 4.1.3 on 2022-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_books_author_name_alter_books_book_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="author_name",
            field=models.CharField(max_length=10000, null=True, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="books",
            name="book_name",
            field=models.CharField(
                max_length=10000, null=True, verbose_name="Название книги"
            ),
        ),
        migrations.AlterField(
            model_name="books",
            name="description",
            field=models.CharField(
                max_length=10000, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="books",
            name="genre",
            field=models.CharField(max_length=10000, null=True, verbose_name="Жанр"),
        ),
    ]
