# Generated by Django 4.1.4 on 2023-05-16 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_author_id_alter_books_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='genre_id',
        ),
    ]
