# Generated by Django 4.1.3 on 2022-12-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_books_author_name_alter_books_book_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="description",
            field=models.TextField(
                max_length=10000, null=True, verbose_name="Описание"
            ),
        ),
    ]
