# Generated by Django 4.1.4 on 2022-12-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_link',
            field=models.URLField(max_length=10000, null=True, verbose_name='Ссылка на книгу'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pic_link',
            field=models.URLField(max_length=10000, null=True, verbose_name='Ссылка на картинку'),
        ),
    ]
