# Generated by Django 4.1.4 on 2023-05-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_books_book_link_remove_books_pic_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
    ]
