# Generated by Django 4.1.3 on 2022-12-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="adding_date", new_name="creat_date",
        ),
    ]
