# Generated by Django 4.1.3 on 2022-12-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0002_rename_adding_date_users_creat_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_name",
                    models.CharField(max_length=100, null=True, verbose_name="Имя"),
                ),
                (
                    "creat_date",
                    models.DateField(null=True, verbose_name="Дата добавления"),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "db_table": "genres",
            },
        ),
        migrations.DeleteModel(name="Users",),
    ]
