# Generated by Django 4.1.3 on 2022-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0003_genres_delete_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genres",
            name="genre_name",
            field=models.CharField(max_length=10000, null=True, verbose_name="Имя"),
        ),
    ]
