# Generated by Django 4.1.4 on 2022-12-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_genres_description_genres_picture_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='creat_date',
        ),
    ]
