# Generated by Django 4.1.4 on 2023-05-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('books', '0003_remove_books_author_id_remove_books_genre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_link', models.URLField(max_length=10000, null=True, verbose_name='Ссылка на картинку')),
                ('book_link', models.URLField(max_length=10000, null=True, verbose_name='Ссылка на книгу')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.sources')),
            ],
            options={
                'verbose_name': 'Источник книг',
                'verbose_name_plural': 'Источники книг',
                'db_table': 'books_sources',
            },
        ),
    ]
