# Generated by Django 4.1.4 on 2023-05-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookssources',
            name='price',
            field=models.IntegerField(default=328, verbose_name='Цена'),
        ),
    ]
