# Generated by Django 4.1.4 on 2023-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='days',
            field=models.IntegerField(null=True, verbose_name='Время прочтения в днях'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=10000, null=True, verbose_name='Отзыв'),
        ),
    ]
