# Generated by Django 4.1.4 on 2023-05-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, null=True, verbose_name='Название подборки')),
                ('status', models.IntegerField(default=1, verbose_name='Статус активности')),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
                'db_table': 'sections',
            },
        ),
    ]
