# Generated by Django 4.1.4 on 2023-05-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='status',
        ),
        migrations.AddField(
            model_name='sources',
            name='stactus',
            field=models.IntegerField(default=1, verbose_name='Статус активности'),
        ),
    ]
