# Generated by Django 4.1.4 on 2023-05-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_remove_sources_status_sources_stactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sources',
            old_name='stactus',
            new_name='status',
        ),
    ]
