# Generated by Django 4.1.4 on 2023-05-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0006_authors_author_description'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authors')),
                ('books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
            options={
                'verbose_name': 'Авторы книг',
                'verbose_name_plural': 'Авторы книг',
                'db_table': 'books_authors',
            },
        ),
    ]
