# Generated by Django 4.1.4 on 2023-05-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_authors_author_description'),
        ('books', '0003_remove_books_author_id_remove_books_genre_id'),
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_authors',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='authors.authors'),
        ),
        migrations.AlterField(
            model_name='books_authors',
            name='books_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.books'),
        ),
    ]
